
= Datakind Mining Project
krishna bhogaonker <cyclotomiq@gmail.com>
:author: Krishna Bhogaonker
:email: cyclotomiq@gmail.com
:revnumber: v0.01
:revdate:   
:revremark: README
:description: This document provides a description and links to packages developed by me for the Datakind mining project. 
:doctype: article
:toc:
:toclevels: 4                                                       
:toc-title: Table of Contents 
:source-highlighter: coderay
:sectnum:
:listing-caption: Listing
:stylesdir: /home/krishnab/Dropbox/backup/computer/asciidoctor/stylesheet-factory/asciidoctor-stylesheet-factory/stylesheets
:stylesheet: colony.css
:imagedir: ./images/
:experimental:                                                      
:imagesdir: ./img           
:keywords: datakind, spatial analysis, machine learning, statistics, python
:stem: latexmath

== Mining Data Acquisition Package

This is a python package that provides a simple API to google-earth-engine to facilitate the download of satellite imagery. The user will input the imagery collection of interest, the beginning and end dates, and a file of mine locations. The package will query the appropriate imagery from earth engine and download the GeoTiff images to the indicated folder.
This package will also facilitate download of relevant vector or raster layers necessary to create features for the mining model.

Note that credentials to access Earth Engine must be obtained separately through a request to Google.

== Point Imagery Data Requests

A Point Imagery Data request refers to a set of point latitude/longitude locations for which imagery is requested. The path to the shapefile or GeoJSON file is provided with the `data-gather` request.

[TODO fill in details] 

The Help screen for the package provides details about how to execute downloads of the data. 



Current Status (12/08/2017): pre-alpha

The basic request for point imagery data is completed and working. There are some issues with the links since migrating to the full github repo and reorganizing some files. Working to fix those. Also working to fix some of the issues with the image metadata provided for each image. 




